# Generated by Django 5.2.8 on 2025-12-10 19:49

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility'), ('balance', 'Balance'), ('plyometric', 'Plyometric'), ('olympic', 'Olympic Lifting'), ('powerlifting', 'Powerlifting')], max_length=50)),
                ('muscle_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('equipment_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=50)),
                ('video_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('instructions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='workouts_ex_name_5d1c33_idx'), models.Index(fields=['category'], name='workouts_ex_categor_79dbc6_idx'), models.Index(fields=['difficulty'], name='workouts_ex_difficu_d7fa80_idx'), models.Index(fields=['category', 'difficulty'], name='workouts_ex_categor_a4cc1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(blank=True, help_text='Height in centimeters', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('fitness_goal', models.CharField(choices=[('strength', 'Strength Training'), ('cardio', 'Cardiovascular Health'), ('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('general', 'General Fitness')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Estimated duration in minutes', null=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=50)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='workouts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('rest_period', models.IntegerField(default=60, help_text='Rest period in seconds')),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='planned', max_length=50)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.userprofile')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.workout')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('perceived_exertion', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workouts.workoutsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='workouts_us_user_id_b24c24_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['creator'], name='workouts_wo_creator_1851cd_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['is_public'], name='workouts_wo_is_publ_768376_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['difficulty'], name='workouts_wo_difficu_4598e9_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['-created_at'], name='workouts_wo_created_eedbfb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutexercise',
            unique_together={('workout', 'order')},
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user'], name='workouts_wo_user_id_44c4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['workout'], name='workouts_wo_workout_e4dd61_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['status'], name='workouts_wo_status_e8689a_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['-created_at'], name='workouts_wo_created_d7e4b1_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'status'], name='workouts_wo_user_id_8a43bb_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', '-completed_at'], name='workouts_wo_user_id_cb6f02_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciselog',
            index=models.Index(fields=['session'], name='workouts_ex_session_e41909_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciselog',
            index=models.Index(fields=['exercise'], name='workouts_ex_exercis_2b9873_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciselog',
            index=models.Index(fields=['created_at'], name='workouts_ex_created_7f944d_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciselog',
            index=models.Index(fields=['session', 'exercise'], name='workouts_ex_session_c11484_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciselog',
            index=models.Index(fields=['exercise', '-created_at'], name='workouts_ex_exercis_1d8f8f_idx'),
        ),
    ]
